spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/packid_dev
    username: packid_dev
    password: packid_dev
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # em dev Ã© ok deixar update

server:
  port: 8080

logging:
  level:
    root: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
